/**
 * Dummy Data Service
 * Provides mock data for development when Hygraph is not configured
 */

import type { Category, MenuItem, Promotion } from '@/types'

export const dummyCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Burgers',
    slug: 'burgers',
    description: 'Juicy, flavorful burgers made with premium ingredients',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-2',
    name: 'Pizza',
    slug: 'pizza',
    description: 'Authentic Italian-style pizzas with fresh toppings',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-3',
    name: 'Salads',
    slug: 'salads',
    description: 'Fresh, healthy salads with premium ingredients',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-4',
    name: 'Desserts',
    slug: 'desserts',
    description: 'Sweet treats to satisfy your cravings',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'cat-5',
    name: 'Beverages',
    slug: 'beverages',
    description: 'Refreshing drinks and beverages',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800',
    displayOrder: 5,
    isActive: true,
  },
]

export const dummyMenuItems: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Classic Cheeseburger',
    slug: 'classic-cheeseburger',
    description: 'Juicy beef patty with melted cheese, fresh lettuce, tomato, and our special sauce',
    images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800'],
    category: dummyCategories[0],
    basePrice: 12.99,
    nutrition: {
      calories: 650,
      protein: 35,
      carbs: 45,
      fat: 35,
      fiber: 3,
      sugar: 8,
      sodium: 1200,
    },
    ingredients: ['Beef patty', 'Cheddar cheese', 'Lettuce', 'Tomato', 'Onion', 'Pickles', 'Special sauce', 'Bun'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isSpicy: false,
    isHalal: false,
    isVegetarian: false,
    isVegan: false,
    isAvailable: true,
    sizes: [
      { id: 'size-1', name: 'Regular', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-2', name: 'Large', priceModifier: 3.00, calorieModifier: 200 },
    ],
    addOns: [
      { id: 'addon-1', name: 'Extra Cheese', description: 'Add more cheese', price: 1.50, calorieModifier: 100, category: 'extra', isAvailable: true },
      { id: 'addon-2', name: 'Bacon', description: 'Crispy bacon strips', price: 2.50, calorieModifier: 150, category: 'topping', isAvailable: true },
      { id: 'addon-3', name: 'Avocado', description: 'Fresh avocado slices', price: 2.00, calorieModifier: 80, category: 'topping', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 1,
  },
  {
    id: 'item-2',
    name: 'Spicy Chicken Burger',
    slug: 'spicy-chicken-burger',
    description: 'Crispy chicken breast with spicy mayo, lettuce, and pickles',
    images: ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800'],
    category: dummyCategories[0],
    basePrice: 11.99,
    nutrition: {
      calories: 580,
      protein: 38,
      carbs: 42,
      fat: 28,
      fiber: 2,
      sugar: 6,
      sodium: 1100,
    },
    ingredients: ['Chicken breast', 'Spicy mayo', 'Lettuce', 'Pickles', 'Bun'],
    allergens: ['Gluten', 'Eggs'],
    isSpicy: true,
    isHalal: true,
    isVegetarian: false,
    isVegan: false,
    isAvailable: true,
    sizes: [
      { id: 'size-3', name: 'Regular', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-4', name: 'Large', priceModifier: 2.50, calorieModifier: 150 },
    ],
    addOns: [
      { id: 'addon-4', name: 'Extra Spicy Sauce', description: 'Add more heat', price: 0.50, calorieModifier: 20, category: 'sauce', isAvailable: true },
      { id: 'addon-5', name: 'Jalapeños', description: 'Fresh jalapeño slices', price: 1.00, calorieModifier: 10, category: 'topping', isAvailable: true },
    ],
    spiceLevels: [
      { id: 'spice-1', name: 'Mild', level: 1, description: 'Slightly spicy' },
      { id: 'spice-2', name: 'Medium', level: 3, description: 'Moderately spicy' },
      { id: 'spice-3', name: 'Hot', level: 5, description: 'Very spicy' },
    ],
    displayOrder: 2,
  },
  {
    id: 'item-3',
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    description: 'Classic Italian pizza with fresh mozzarella, tomato sauce, and basil',
    images: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800'],
    category: dummyCategories[1],
    basePrice: 14.99,
    nutrition: {
      calories: 720,
      protein: 28,
      carbs: 85,
      fat: 28,
      fiber: 4,
      sugar: 8,
      sodium: 1400,
    },
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella cheese', 'Fresh basil', 'Olive oil'],
    allergens: ['Gluten', 'Dairy'],
    isSpicy: false,
    isHalal: false,
    isVegetarian: true,
    isVegan: false,
    isAvailable: true,
    sizes: [
      { id: 'size-5', name: 'Small (10")', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-6', name: 'Medium (12")', priceModifier: 4.00, calorieModifier: 200 },
      { id: 'size-7', name: 'Large (14")', priceModifier: 7.00, calorieModifier: 400 },
    ],
    addOns: [
      { id: 'addon-6', name: 'Extra Cheese', description: 'More mozzarella', price: 2.00, calorieModifier: 150, category: 'extra', isAvailable: true },
      { id: 'addon-7', name: 'Olives', description: 'Black olives', price: 1.50, calorieModifier: 30, category: 'topping', isAvailable: true },
      { id: 'addon-8', name: 'Mushrooms', description: 'Fresh mushrooms', price: 2.00, calorieModifier: 20, category: 'topping', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 3,
  },
  {
    id: 'item-4',
    name: 'Pepperoni Pizza',
    slug: 'pepperoni-pizza',
    description: 'Classic pepperoni pizza with mozzarella and tomato sauce',
    images: ['https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800'],
    category: dummyCategories[1],
    basePrice: 16.99,
    nutrition: {
      calories: 850,
      protein: 35,
      carbs: 88,
      fat: 38,
      fiber: 3,
      sugar: 7,
      sodium: 1800,
    },
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella cheese', 'Pepperoni'],
    allergens: ['Gluten', 'Dairy'],
    isSpicy: false,
    isHalal: false,
    isVegetarian: false,
    isVegan: false,
    isAvailable: true,
    sizes: [
      { id: 'size-8', name: 'Small (10")', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-9', name: 'Medium (12")', priceModifier: 4.00, calorieModifier: 200 },
      { id: 'size-10', name: 'Large (14")', priceModifier: 7.00, calorieModifier: 400 },
    ],
    addOns: [
      { id: 'addon-9', name: 'Extra Pepperoni', description: 'More pepperoni', price: 3.00, calorieModifier: 200, category: 'topping', isAvailable: true },
      { id: 'addon-10', name: 'Extra Cheese', description: 'More mozzarella', price: 2.00, calorieModifier: 150, category: 'extra', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 4,
  },
  {
    id: 'item-5',
    name: 'Caesar Salad',
    slug: 'caesar-salad',
    description: 'Fresh romaine lettuce with Caesar dressing, croutons, and parmesan cheese',
    images: ['https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800'],
    category: dummyCategories[2],
    basePrice: 9.99,
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 18,
      fat: 22,
      fiber: 4,
      sugar: 4,
      sodium: 800,
    },
    ingredients: ['Romaine lettuce', 'Caesar dressing', 'Croutons', 'Parmesan cheese'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isSpicy: false,
    isHalal: false,
    isVegetarian: false,
    isVegan: false,
    isAvailable: true,
    sizes: [
      { id: 'size-11', name: 'Regular', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-12', name: 'Large', priceModifier: 3.00, calorieModifier: 150 },
    ],
    addOns: [
      { id: 'addon-11', name: 'Grilled Chicken', description: 'Add grilled chicken', price: 4.00, calorieModifier: 200, category: 'extra', isAvailable: true },
      { id: 'addon-12', name: 'Extra Parmesan', description: 'More parmesan cheese', price: 1.50, calorieModifier: 80, category: 'extra', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 5,
  },
  {
    id: 'item-6',
    name: 'Garden Salad',
    slug: 'garden-salad',
    description: 'Mixed greens with tomatoes, cucumbers, carrots, and your choice of dressing',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800'],
    category: dummyCategories[2],
    basePrice: 8.99,
    nutrition: {
      calories: 180,
      protein: 5,
      carbs: 15,
      fat: 12,
      fiber: 6,
      sugar: 8,
      sodium: 300,
    },
    ingredients: ['Mixed greens', 'Tomatoes', 'Cucumbers', 'Carrots', 'Dressing'],
    allergens: [],
    isSpicy: false,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isAvailable: true,
    sizes: [
      { id: 'size-13', name: 'Regular', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-14', name: 'Large', priceModifier: 2.50, calorieModifier: 100 },
    ],
    addOns: [
      { id: 'addon-13', name: 'Avocado', description: 'Fresh avocado', price: 2.00, calorieModifier: 80, category: 'topping', isAvailable: true },
      { id: 'addon-14', name: 'Nuts', description: 'Mixed nuts', price: 1.50, calorieModifier: 100, category: 'topping', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 6,
  },
  {
    id: 'item-7',
    name: 'Chocolate Brownie',
    slug: 'chocolate-brownie',
    description: 'Rich, fudgy chocolate brownie served warm with vanilla ice cream',
    images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800'],
    category: dummyCategories[3],
    basePrice: 6.99,
    nutrition: {
      calories: 450,
      protein: 6,
      carbs: 55,
      fat: 22,
      fiber: 3,
      sugar: 40,
      sodium: 200,
    },
    ingredients: ['Chocolate', 'Butter', 'Sugar', 'Flour', 'Eggs', 'Vanilla ice cream'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isSpicy: false,
    isHalal: false,
    isVegetarian: true,
    isVegan: false,
    isAvailable: true,
    sizes: [],
    addOns: [
      { id: 'addon-15', name: 'Extra Ice Cream', description: 'More vanilla ice cream', price: 1.50, calorieModifier: 150, category: 'side', isAvailable: true },
      { id: 'addon-16', name: 'Caramel Sauce', description: 'Drizzle of caramel', price: 0.50, calorieModifier: 50, category: 'sauce', isAvailable: true },
    ],
    spiceLevels: [],
    displayOrder: 7,
  },
  {
    id: 'item-8',
    name: 'Fresh Lemonade',
    slug: 'fresh-lemonade',
    description: 'Freshly squeezed lemonade with a hint of mint',
    images: ['https://images.unsplash.com/photo-1523677011783-c91d1bbe2fdc?w=800'],
    category: dummyCategories[4],
    basePrice: 4.99,
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 30,
      fat: 0,
      fiber: 0,
      sugar: 28,
      sodium: 10,
    },
    ingredients: ['Fresh lemons', 'Sugar', 'Water', 'Mint'],
    allergens: [],
    isSpicy: false,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isAvailable: true,
    sizes: [
      { id: 'size-15', name: 'Small (16oz)', priceModifier: 0, calorieModifier: 0 },
      { id: 'size-16', name: 'Medium (20oz)', priceModifier: 1.00, calorieModifier: 30 },
      { id: 'size-17', name: 'Large (24oz)', priceModifier: 2.00, calorieModifier: 60 },
    ],
    addOns: [],
    spiceLevels: [],
    displayOrder: 8,
  },
]

export const dummyPromotions: Promotion[] = [
  {
    id: 'promo-1',
    code: 'WELCOME10',
    name: 'Welcome Discount',
    description: '10% off your first order',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 20,
    maxDiscountAmount: 10,
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 year from now
    isActive: true,
    usageLimit: 1000,
    usedCount: 0,
  },
  {
    id: 'promo-2',
    code: 'SAVE5',
    name: 'Flat $5 Off',
    description: 'Save $5 on orders over $30',
    discountType: 'fixed',
    discountValue: 5,
    minOrderAmount: 30,
    maxDiscountAmount: 5,
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
    usageLimit: undefined,
    usedCount: 0,
  },
]

/**
 * Helper function to check if we should use dummy data
 */
export function shouldUseDummyData(): boolean {
  return !process.env.NEXT_PUBLIC_HYGRAPH_ENDPOINT || process.env.NEXT_PUBLIC_HYGRAPH_ENDPOINT === ''
}

